language: haxe

os:
  - linux

haxe:
  - "3.4.7"
  - development

matrix:
  allow_failures:
    - haxe: "3.4.7"

branches:
  only:
    - master
    - dev

install:
  - haxelib install electron
  - haxelib install dox
  - haxelib dev atom .

script:
  - rm -rf src/
  - haxe api.hxml
  - haxe doc.hxml
  - haxe --cwd example build.hxml
