language: haxe

os:
  - linux

haxe:
  - "3.4.4"
  - development

matrix:
  allow_failures:
    - haxe: development

branches:
  only:
    - master
    - dev

script:
  - haxelib install electron
  - haxelib install dox
  - haxelib dev atom .
  - haxe run.hxml
  - neko run.n
  - haxe doc.hxml
  - haxe --cwd example build.hxml
